### ISSUE TITLE
labeling of dimension buttons

### ISSUE THREAD

**Issue by touretzkyds** [jxu/Word2VecDemo#23]
The dimension buttons used to be labeled [gender] and [age], but in the latest release the labels are initialized to "...". This is a bug. 

Note: clicking on the Submit buttons in the user-defined dimensions panel fixes the labels.

**Comment by touretzkyds** [comment]
The initial user-defined dimension names are "[gender]" and "[age]" with square brackets. If I click submit, the axis labels become "[[gender]]" and "[[age]]" with double brackets. This is a bug.

We should omit the square brackets from the user-defined dimension names when initializing the text box.

**Comment by jxu** [comment]
Ok hopefully this should be fixed now. It was caused by a change I made to how the default text boxes were filled. Before it was the user inputs were filled and then read to process the model. Now user inputs are filled and model is initially processed using internal defaults. For this change I added two new functions that format and unformat feature names with brackets. Internally feature names always have brackets to distinguish them from regular words.
