### ISSUE TITLE
Computation of residual feature vector

### ISSUE THREAD

**Issue by jxu** [jxu/Word2VecDemo#3]
I am unsure of how the calculation of residual feature, the "no age no gender" feature is derived.

Trying to understand it from the original code: let `gender` and `age` be the features corresponding to the average differences of the selected pairs (called `MEAN_gender` and `MEAN_age` in the original code). The computation is done as 

```
man_no_gender = man - (man dot gender) gender
man_residual = man_no_gender - (man_no_gender dot age) age
man_residual_coord = 1 - (man dot norm(man_residual))
```

I don't know the theoretical justification for computing the residual coordinate, why even use the one subtraction. I am a little rusty on my linear algebra.

**Comment by jxu** [comment]
I am a little rusty on my linear algebra but I don't see any nice way of expressing the residual feature vector as a simple projection of `man dot residual`.

**Comment by jxu** [comment]
Here is my intuition. Cosine similarity is a value between -1 and 1. We can compute a cosine similarity between any word vector and age, similarly for gender. But there is no guarantee similarities should add up to 1 or anything like that. I may need to ask online for some theoretical justification.

**Comment by touretzkyds** [comment]
Okay, here's a quick explanation of why this works.

In a simplified ideal world, the vector (king - queen) would exactly equal the vector (boy - girl) or (brother - sister), and would point in the "gender" direction in semantic space. However, with a real dataset this is never the case because of idiomatic phrases such as "king of beers" or "mother of invention" or "best boy".  So in order to derive a vector that points in the general direction of "gender", we subtract each of these gender pairs and then average the results together. Finally, we normalize the average, giving us a UNIT VECTOR that points in the general direction of "gender".

We do the same kind of thing to get a unit vector for "age".

Now if we want a version of "man" with gender and age deleted, we need to measure the component of man in the "gender" direction and subtract that out.  (man dot gender) gives us the length of the projection of man in the gender direction; this is a scalar. We use this as a multiplier to scale the gender vector, and subtract that from "man" to get "man_no_gender", i.e., "man" with its gender component subtracted out. This is just like subtracting the first principal component from a vector to get the residual.

Given man_no_gender, if we want to now remove the age component, we take (man_no_gender dot age) and use this to scale the "age" unit vector, and subtract the result from man_no_gender to get man_no_gender_no_age, which in the code is called man_residual. Again, this is like subtracting the second principal component from a vector once you've removed the first principal component. The only difference is that principal components are orthogonal, while semantic vectors are not, so the subtraction has to be done sequentially in our case; you can't compute both dot products in parallel.

Thanks for the tip about "watch". I hadn't used that feature before.

**Comment by jxu** [comment]
Yes, I agree about subtracting out the projections to get a "man_residual" vector, representing "man" with the gender and age directions subtracted out. So man projected onto (normalized) "man_residual" to get something akin to how much of "man" vector lies in the "man_residual" direction? Then the 1 - projection is unnecessary since we have already subtracted out gender and age directions?

If I recall correctly, with PCA with orthogonal PCs then we can use the sum of eigenvalues as explained variance, which doesn't apply here since our components aren't orthogonal.

**Comment by touretzkyds** [comment]
The residual is not 1-(man dot man_nogender_noage). The residual is 1-(man dot MEAN_nogender_noage).The 1-x is needed because the "residual" dimension is supposed to show us how far away the residual is from the words that make up the age and gender dimensions. Thus "man" and "woman" are both well aligned with the  MEAN_nogender_noage vector, while "refrigerator"  is not, so its dot product is small, and the 1-x gives it a high residual.

**Comment by jxu** [comment]
I see, about the mean_nogender_noage / residual. 
I still don't get the 1-x, unless we make an assumption that (word dot mean_no_gender_noage) would be close to 1. residual is a unit vector but in general a word isn't? And why do we use 1-x if we have already subtracted out the age and gender components in computing residual?

**Comment by touretzkyds** [comment]
We use 1-x to support a graphical convention that makes "man" and "woman" close together, while "refrigerator" is far away from both of them. It's the difference between cosine similarity (1 = maximally similar) and semantic distance (0 = maximally similar).

Maybe we should change the axis label from "ageless genderless" to "residual". Refrigerator has a high residual.

**Comment by jxu** [comment]
Ok. I need to implement the mean calculation but my dataset uses different word embeddings and residuals didn't appear to be close to 0 for any words (also I had to replace refrigerator with chair since refrigerator wasn't in my 10k tokens, but same idea)

**Comment by touretzkyds** [comment]
Some words are less affected by idiomatic asymmetries, e.g., "niece" and "nephew" or "waiter" and "waitress". So they should map to nearby points when you subtract age and gender. If they don't then something is wrong with your calculation.

**Comment by touretzkyds** [comment]
You might want to go back to the original dataset and verify that your code reproduces the previous model's behavior.

**Comment by jxu** [comment]
![Screenshot from 2021-06-15 16-21-58](https://user-images.githubusercontent.com/7989982/122118265-d6d69200-cdf5-11eb-9812-157900e5233a.png)


I didn't verify the numbers but I think the calculations are correct. There's a nice separation between genders and age points. Under the convention that 0 dot product means most similar, the objects like chair and computer are much closer to "genderless ageless" vector than the other family member words. But it is confusing for people who don't know the internals of vector projection that 0 means more similar so that should perhaps be noted.

**Comment by jxu** [comment]
![Screenshot from 2021-06-15 16-32-35](https://user-images.githubusercontent.com/7989982/122119526-4f8a1e00-cdf7-11eb-9aa2-88754f0100bf.png)

Here is the plot with word vectors normalized, which makes everything fall conveniently into [-1,1]. Both plots are without the 1-residual projection

**Comment by touretzkyds** [comment]
Yes, this is looking very good!
